apiVersion: v1
kind: Secret
metadata:
  name: task-api-secrets
type: Opaque
stringData:
  # NOTE: These are placeholders. In production, use Azure Key Vault or Sealed Secrets
  # DO NOT commit real secrets to Git
  database-url: "postgresql+asyncpg://postgres:CHANGE_ME@postgres:5432/taskdb"
  secret-key: "CHANGE_ME_TO_RANDOM_STRING_IN_PRODUCTION"
